osx_image: xcode10.2
language: objective-c
cache:
  directories:
  - Carthage
env:
  global:
  - FRAMEWORK_NAME=SwipeViewController
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push --skip-import-validation --skip-tests --allow-warnings
script:
- set -o pipefail && xcodebuild test -scheme $FRAMEWORK_NAME -destination 'platform=iOS
  Simulator,name=iPhone XS,OS=12.1' ONLY_ACTIVE_ARCH=YES | xcpretty
deploy:
  provider: releases
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDhIHhQpGOE1ZC4UYgO5iDflARqIYsYZsMqq/qWdfPK1uQUymJIZu7rjoxqkppMV7v6S9xeEMMDq8AsN3wcd2Z2jnbHZttX9wrmk2PXEvcfFTs6kGvWJWrmJeG8yvKQSZzXx6kyQMDO13NuoU8dLRR4ZdIgHMNA6I4RguP7M/rjGx5Gfl+XFkdixZM44lvF+UaX0myRcpVJzqAgDDzM5XncX8+w9k5Ss86EAZ9tCPqioR23EZVlb6pKiIGnWqXv/Upl+QOoCO4A99zVnrxSQznW5HkuIJikMenuLZpbPjMCpn+Jws3bLUNjTqK7BgJXyBBa4WX3ZcVa+aGUr5FlSsrnqF1qH9IEKql2C+tcpW4xluBMjwo1IZpBm0y/nXWWccTL2gKeYvYxmrqzgJqve4X2HVMHlCt+aEpt+0MbRJMt21QNpDmzn+7wUfp4x73XtntblT9fabJldZqKtmANY9zNUKRBsA3QZvHMTwOJKNMpx2EY2fTJOG6vZMoEqwp4HZQW9sQORKHcDJl2HI7QTsPqrdrs5Fm0ewr7Jbfjrx5pnsSQ54uKGdZjlwKQutJqT7bz95+RDTJu4DUEjnbFT94XAR2NdGcUfKD9G5uMuIb/pp9j0ZEsBJlkxmgTaYzsGefcASfd+Kys2d0BJBnwl6NuJO8Up6POESH6IO//SxXNTw==
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: fortmarek/SwipeViewController
    tags: true